language: go
go:
        - tip
        - 1.3
script: go get code.google.com/p/go.tools/cmd/vet && go get github.com/golang/lint/golint && go get github.com/kisom/whitelist/... && $HOME/gopath/bin/golint *.go && go test github.com/kisom/whitelist/... && go vet github.com/kisom/whitelist/...
notifications:
        email:
                recipients:
                        - coder@kyleisom.net
                on_success: change
                on_failure: change
